udpServer:
	gcc udpServer.c -o udpServer
	./udpServer
	rm udpServer

udpClient1:
	gcc udpClient.c -o udpClient1
	./udpClient1
	rm udpClient1

udpClient2:
	gcc udpClient.c -o udpClient2
	./udpClient2
	rm udpClient2

tcpServer:
	gcc tcpServer.c -o tcpServer
	./tcpServer
	rm tcpServer

tcpClient1:
	gcc tcpClient.c -o tcpClient1
	./tcpClient1
	rm tcpClient1

tcpClient2:
	gcc tcpClient.c -o tcpClient2
	./tcpClient2
	rm tcpClient2

