tcpServer:
	gcc tcpServer.c -o tcpServer
	./tcpServer
	rm tcpServer

udpServer:
	gcc udpServer.c -o udpServer
	./udpServer
	rm udpServer

tcpClient:
	gcc tcpClient.c -o tcpClient
	./tcpClient
	rm tcpClient

udpClient:
	gcc udpClient.c -o udpClient
	./udpClient
	rm udpClient

